name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # Root folder containing index.html
          force_orphan: true       # Create gh-pages branch from scratch
          keep_files: false        # Remove old files
          user_name: "Jaggu07-P"
          user_email: "jagannathms07@gmail.com"  # Replace with your GitHub email
