name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main   # Make sure your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # Root folder (index.html must be here)
          keep_files: false
